### ISSUE TITLE
Avoid runtime overhead of python version checks

### ISSUE THREAD

**Issue by asottile** [Yelp/named_decorator#6]
https://github.com/Yelp/named_decorator/blob/250fa7d0cb00bccd311cd940f4fa7919fe7a91ec/five.py#L18-L21

The usual way to do this is (at the module scope)

```python
if PY2:
    def get_function_code(...):
        ...
else:
    ...
```

This avoids branches at runtime

**Comment by ArnaudBrousseau** [comment]
Good catch
